
name: Linkumori crx packaging 

# Add permissions block
permissions:
  contents: write  # This is needed for creating releases

on:
  release:
    types: [created]

jobs:
  pack-extension:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Create a clean directory without the PEM file
      - name: Prepare clean directory
        run: |
          mkdir clean_ext
          rsync -av --exclude='*.pem' --exclude='.git*' --exclude='.github' . clean_ext/

      # Install Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      # Pack the extension
      - name: Pack Extension
        run: |
          chromium-browser --pack-extension="$(pwd)/clean_ext"
          mv clean_ext.crx "${{ github.event.repository.name }}.crx"
          
      # Upload CRX to release with explicit token
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}.crx
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Cleanup
      - name: Cleanup
        if: always()
        run: rm -rf clean_ext
